
services:
  playwright:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ws-notion
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: pnpm run test
    tty: true
